- name: configuration mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: installed mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysql
      state: present
      enabled: yes

