- name: configuration mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install MySQL libraries
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3.9

  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.bsdaws82s.site
    register: mysql_info
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "mysql info: {{ mysql_info }}"


  

